name: 'Algebras Translation Status'
description: 'Check translation status in your i18n-enabled NextJS project'
author: 'algebras-ai'
branding:
  icon: 'globe'
  color: 'blue'

inputs:
  file_pattern:
    description: 'Optional file pattern for localization files'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Algebras CLI
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/algebras-ai/algebras-cli.git
    
    - name: Check translation status
      shell: bash
      run: |
        if [ -n "${{ inputs.file_pattern }}" ]; then
          algebras configure --path-rules "${{ inputs.file_pattern }}"
        fi
        algebras status
        if [ $? -ne 0 ]; then
          echo "::error::Translation status check failed! Some translations are missing or outdated."
          exit 1
        fi 